on:
  push:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.ref_name}}
steps: 
- uses: actions/checkout@v4

-name : Install Dependencies
  run: npm install

-name : Deploy

  env:
    SANITY_AUTH_TOKEN: ${{ secrets.SANITY_AUTH_TOKEN }}
    SANITY_STUDIO_HOST: ${{ secrets.SANITY_STUDIO_HOST }}
 run: npm run deploy -- --yes