on:
  push:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.ref_name}}
steps: 
- uses: actions/checkout@v4

-name : Install Dependencies
  run: npm install

-name : Deploy
 run: npm run deploy -- --yes